name: Generate JSON on Push

# Trigger workflow on push to the main branch
on:
    push:
        branches:
            - main

# Define the jobs to be run
jobs:
    generate-json:
        runs-on: ubuntu-latest

        steps:
            # Step 1: Check out the repository
            - name: Check out code
              uses: actions/checkout@v3

            # Step 2: Set up Python
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.x" # Specify the Python version

            # Step 3: Install dependencies (if any)
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  # Install any required Python packages here, if necessary
                  pip install -r requirements.txt || true

            # Step 4: Run the script
            - name: Run generate_json.py
              run: |
                  python generate_json.py

            # Step 5: Commit and push the updated JSON
            - name: Commit and push changes
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  git add fonts.json
                  git commit -m "Update fonts.json [skip ci]" || echo "No changes to commit"
                  git push
